apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deno-module-visualizer
  annotations:
    autoscaling.knative.dev/maxScale: "5"
spec:
  template:
    spec:
      containerConcurrency: 20
      containers:
      - image: gcr.io/stardust-156404/deno-module-visualizer:v1beta1
        resources:
          limits:
            cpu: "1"
            memory: 128Mi
